version: "3.8"

services:
  mysql:
    image: mysql:5.7  # Use a stable version
    restart: always
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mydb
      MYSQL_USER: user
      MYSQL_PASSWORD: root
      MYSQL_ROOT_HOST: "%"  # Allow external connections
    ports:
      - "3306:3306"
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - mysql_data:/var/lib/mysql  # Persist MySQL data

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    restart: always
    container_name: phpmyadmin
    environment:
      PMA_HOST: mysql  # Ensure correct MySQL hostname
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: root
    ports:
      - "8085:80"
    depends_on:
      - mysql  # Ensure MySQL starts first

volumes:
  mysql_data:  # Persistent storage for MySQL
